apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote
        envFrom:
        - configMapRef:
            name: vote-options
            optional: true
